/*
 * (C) Copyright 2018.  Eugene Zrazhevsky and others.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * Contributors:
 * Eugene Zrazhevsky <eugene.zrazhevsky@gmail.com>
 */

package com.mmz.specs.application.gui.panels.service;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;

public class SimpleImageViewer extends JPanel {
    private static final RESIZE_POLICY DEFAULT_RESIZE_POLICY = RESIZE_POLICY.FIT_TO_SCREEN;
    final private BufferedImage bufferedImage;
    private final int DEFAULT_UNIT_INCREMENT_SPEED = 16;
    private RESIZE_POLICY currentResizePolicy = DEFAULT_RESIZE_POLICY;
    private JPanel contentPane;
    private JLabel imageLabel;
    private JScrollPane scrollPane;
    private float currentSize = 1.0f;
    private Thread resizeThread = null;

    public SimpleImageViewer(BufferedImage image) {
        this.bufferedImage = image;
        initGui();
        initImageContextMenu();

        updateImage(image);

        initComponentListeners(image);

        initMouseListeners();

        centerImage();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane = new JScrollPane();
        contentPane.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(0);
        imageLabel.setHorizontalTextPosition(0);
        imageLabel.setText("");
        scrollPane.setViewportView(imageLabel);
    }

    private void centerImage() {
        Dimension size = scrollPane.getViewport().getViewSize();

        int x = (size.width - imageLabel.getIcon().getIconWidth()) / 2;
        int y = (size.height - imageLabel.getIcon().getIconHeight()) / 2;

        scrollPane.getViewport().setViewPosition(new Point(x, y));
    }

    private Image fitToHeight(Image image) {
        final int width = image.getWidth(null);
        final int height = image.getHeight(null);
        final int componentHeight = getHeight() - scrollPane.getHorizontalScrollBar().getHeight();
        BufferedImage resizedImage = getBufferedImage(image, componentHeight, ((int) ((double) (width * componentHeight))) / height);
        return new ImageIcon(resizedImage).getImage();
    }

    private Image fitToWidth(Image image) {
        final int width = image.getWidth(null);
        final int height = image.getHeight(null);
        final int componentWidth = getWidth() - scrollPane.getVerticalScrollBar().getWidth();
        BufferedImage resizedImage = getBufferedImage(image, ((int) ((double) (componentWidth * height)) / width), componentWidth);
        return new ImageIcon(resizedImage).getImage();
    }

    private Image fitToWindow(Image image) {
        final int width = image.getWidth(null);
        final int height = image.getHeight(null);
        final int componentHeight = getHeight() - scrollPane.getHorizontalScrollBar().getHeight();
        final int componentWidth = getWidth() - scrollPane.getVerticalScrollBar().getWidth();

        final int heightForFitToWidth = (int) ((double) (componentWidth * height)) / width;
        if (heightForFitToWidth > componentHeight) {
            return fitToHeight(image);
        } else {
            return fitToWidth(image);
        }
    }

    private BufferedImage getBufferedImage(Image image, int height, int width) {
        if (height <= 0 && width <= 0) {
            height = image.getHeight(null);
            width = image.getWidth(null);
        }

        System.out.println("final size: " + height + " " + width);

        BufferedImage bufferedImage = null;
        if (!Thread.currentThread().isInterrupted()) {
            bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = bufferedImage.createGraphics();
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                    RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g2.drawImage(image, 0, 0, width, height, null);
            g2.dispose();
        }
        return bufferedImage;

    }

    private void initComponentListeners(BufferedImage image) {
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                updateImage(image);
            }
        });
    }

    private void initGui() {
        setLayout(new GridLayout());
        add(contentPane);
        scrollPane.getVerticalScrollBar().setUnitIncrement(DEFAULT_UNIT_INCREMENT_SPEED);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(DEFAULT_UNIT_INCREMENT_SPEED);
    }

    private void initImageContextMenu() {
        JPopupMenu menu = new JPopupMenu();
        JMenu resizeMenu = new JMenu("Изменить размер");

        JMenuItem screen = new JMenuItem("По размеру окна");
        screen.addActionListener(l -> {
            currentResizePolicy = RESIZE_POLICY.FIT_TO_SCREEN;
            updateImage(bufferedImage);
        });
        resizeMenu.add(screen);

        JMenuItem original = new JMenuItem("Оригинальный размер");
        original.addActionListener(l -> {
            currentResizePolicy = RESIZE_POLICY.ORIGINAL_SIZE;
            updateImage(bufferedImage);
            centerImage();
        });
        resizeMenu.add(original);

        JMenuItem toWidth = new JMenuItem("По ширине");
        toWidth.addActionListener(l -> {
            currentResizePolicy = RESIZE_POLICY.FIT_TO_WIDTH;
            updateImage(bufferedImage);
        });
        resizeMenu.add(toWidth);

        JMenuItem toHeight = new JMenuItem("По высоте");
        toHeight.addActionListener(l -> {
            currentResizePolicy = RESIZE_POLICY.FIT_TO_HEIGHT;
            updateImage(bufferedImage);
        });
        resizeMenu.add(toHeight);

        menu.add(resizeMenu);
        imageLabel.setComponentPopupMenu(menu);

    }

    private void initMouseListeners() {
        imageLabel.setAutoscrolls(true);
        MouseAdapter ma = new MouseAdapter() {
            private Point origin;

            @Override
            public void mouseDragged(MouseEvent e) {
                if (origin != null) {
                    JViewport viewPort = (JViewport) SwingUtilities.getAncestorOfClass(JViewport.class, imageLabel);
                    if (viewPort != null) {
                        int deltaX = origin.x - e.getX();
                        int deltaY = origin.y - e.getY();

                        Rectangle view = viewPort.getViewRect();
                        view.x += deltaX;
                        view.y += deltaY;
                        imageLabel.scrollRectToVisible(view);
                    }
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                origin = new Point(e.getPoint());
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }
        };

        imageLabel.addMouseListener(ma);
        imageLabel.addMouseMotionListener(ma);

        scrollPane.addMouseWheelListener(new MouseAdapter() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                final boolean controlDown = e.isControlDown();
                if (controlDown) {
                    scrollPane.getVerticalScrollBar().setUnitIncrement(0);
                    scrollPane.getHorizontalScrollBar().setUnitIncrement(0);
                    scaleImage(e.getWheelRotation());
                } else {
                    scrollPane.getVerticalScrollBar().setUnitIncrement(DEFAULT_UNIT_INCREMENT_SPEED);
                    scrollPane.getHorizontalScrollBar().setUnitIncrement(DEFAULT_UNIT_INCREMENT_SPEED);
                }

            }
        });
    }

    private Icon resizeImageByCurrentPolicy(BufferedImage bufferedImage) {
        Image image = new ImageIcon(bufferedImage).getImage();

        switch (currentResizePolicy) {
            case ORIGINAL_SIZE: {
                currentSize = 1.0f;
                break;
            }
            case FIT_TO_WIDTH: {
                image = fitToWidth(image);
                currentSize = (float) image.getWidth(null) / bufferedImage.getWidth();
                break;
            }
            case FIT_TO_HEIGHT: {
                image = fitToHeight(image);
                currentSize = (float) image.getWidth(null) / bufferedImage.getWidth();
                break;
            }
            default: {
                image = fitToWindow(image);
                currentSize = (float) image.getWidth(null) / bufferedImage.getWidth();
                break;
            }
        }
        return new ImageIcon(image);
    }

    private void scaleImage(float size) {
        final float MIN_SCALE = 0.2f;
        final float MAX_SCALE = 2.0f;
        if (size > MIN_SCALE && size < MAX_SCALE) {
            updateImage(bufferedImage, size);
        } else {
            if (size < MIN_SCALE) {
                this.currentSize = MIN_SCALE;
            } else {
                this.currentSize = MAX_SCALE;
            }
        }
    }

    private void scaleImage(int rotation) {
        final float size = currentSize + ((float) rotation * .05f);
        currentSize = size;
        if (resizeThread == null) {
            resizeThread = new Thread(() -> {
                scaleImage(size);
            });
            resizeThread.start();
        } else {
            if (resizeThread.isAlive()) {
                resizeThread.interrupt();
                resizeThread = new Thread(() -> {
                    scaleImage(size);
                });
                resizeThread.start();
            } else {
                resizeThread = new Thread(() -> {
                    scaleImage(size);
                });
                resizeThread.start();
            }
        }
    }

    private void updateImage(BufferedImage bufferedImage) {
        imageLabel.setIcon(resizeImageByCurrentPolicy(bufferedImage));
    }

    private void updateImage(BufferedImage bufferedImage, float size) {
        int resizedHeight = (int) (bufferedImage.getHeight() * size);
        int resizedWidth = (int) (bufferedImage.getWidth() * size);

        BufferedImage resized = bufferedImage;
        if (!Thread.currentThread().isInterrupted()) {
            resized = getBufferedImage(bufferedImage, resizedHeight, resizedWidth);
        }

        if (resized != null) {
            imageLabel.setIcon(new ImageIcon(resized));
        }
    }

    public enum RESIZE_POLICY {
        ORIGINAL_SIZE, FIT_TO_SCREEN, FIT_TO_WIDTH, FIT_TO_HEIGHT
    }
}
